#!/bin/sh
case "$1" in
  start)
    if [[ -f /flags/no_menu ]]; then
      echo "No menu flag present...skipping menuing."
      exit
    fi
    /usr/bin/respawn_menu.sh &
    ;;
  stop)
    for KILLPID in `ps | grep 'retroarch' | awk ' { print $1;}'`; do
      kill -9 $KILLPID;
    done
    exit 1
    ;;
  *)
    exit 1
    ;;
esac

exit 0
