name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - uses: actions/upload-artifact@v3
    - name: Install dependencies
      run: make lf2000_defconfig   
    - name: my-artifact
    - with:
        name: hello
        path: output/
