name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: actions/checkout@v3
      run: ./do_release.sh
      run: tar -cf archive.tar output/*

    - name: Run check
      uses: actions/upload-artifacts@v3
      with:
       name: archive
       path: archive.tar
