name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Actually install deps
      run: sudo apt install xgettext 
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ./do_release.sh && tar -cf archive.tar output/*

    - name: Run check
      uses: actions/upload-artifact@v3
      with:
       name: archive
       path: archive.tar
